[2022-11-02 19:17:37,511] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:17:37,703] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:17:37,704] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:18:27,302] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:18:27,480] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:18:27,482] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:18:29,460] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:18:29,637] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:18:29,637] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:18:30,231] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 19:18:30,231] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 19:18:43,249] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:18:43,425] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:18:43,428] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:18:47,850] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:18:48,009] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:18:48,009] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:18:49,919] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:18:50,104] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:18:50,107] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:18:50,699] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 19:18:50,699] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 19:19:04,862] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /store/
Traceback (most recent call last):
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 416, in initial
    self.check_throttles(request)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 359, in check_throttles
    if not throttle.allow_request(request, self):
  File "D:\src\smarterwms\shopee\utils\throttle.py", line 17, in allow_request
    openid = request.auth.openid
AttributeError: 'NoneType' object has no attribute 'openid'
[2022-11-02 19:19:04,862] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /store/
Traceback (most recent call last):
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 416, in initial
    self.check_throttles(request)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 359, in check_throttles
    if not throttle.allow_request(request, self):
  File "D:\src\smarterwms\shopee\utils\throttle.py", line 17, in allow_request
    openid = request.auth.openid
AttributeError: 'NoneType' object has no attribute 'openid'
[2022-11-02 19:19:04,898] [basehttp.py:187] [basehttp:log_message] [ERROR]- "GET /store/?ordering=-update_time HTTP/1.1" 500 116392
[2022-11-02 19:19:04,898] [basehttp.py:187] [basehttp:log_message] [ERROR]- "GET /store/?ordering=-update_time HTTP/1.1" 500 116392
[2022-11-02 19:19:11,512] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /order?max_page=30&record= HTTP/1.1" 301 0
[2022-11-02 19:19:11,512] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /order?max_page=30&record= HTTP/1.1" 301 0
[2022-11-02 19:19:11,636] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /store/all/
Traceback (most recent call last):
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 416, in initial
    self.check_throttles(request)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 359, in check_throttles
    if not throttle.allow_request(request, self):
  File "D:\src\smarterwms\shopee\utils\throttle.py", line 17, in allow_request
    openid = request.auth.openid
AttributeError: 'NoneType' object has no attribute 'openid'
[2022-11-02 19:19:11,636] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /store/all/
Traceback (most recent call last):
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 416, in initial
    self.check_throttles(request)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 359, in check_throttles
    if not throttle.allow_request(request, self):
  File "D:\src\smarterwms\shopee\utils\throttle.py", line 17, in allow_request
    openid = request.auth.openid
AttributeError: 'NoneType' object has no attribute 'openid'
[2022-11-02 19:19:11,659] [basehttp.py:187] [basehttp:log_message] [ERROR]- "GET /store/all/?type=2 HTTP/1.1" 500 116270
[2022-11-02 19:19:11,659] [basehttp.py:187] [basehttp:log_message] [ERROR]- "GET /store/all/?type=2 HTTP/1.1" 500 116270
[2022-11-02 19:19:11,715] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /order/
Traceback (most recent call last):
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 416, in initial
    self.check_throttles(request)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 359, in check_throttles
    if not throttle.allow_request(request, self):
  File "D:\src\smarterwms\shopee\utils\throttle.py", line 17, in allow_request
    openid = request.auth.openid
AttributeError: 'NoneType' object has no attribute 'openid'
[2022-11-02 19:19:11,715] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /order/
Traceback (most recent call last):
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 416, in initial
    self.check_throttles(request)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 359, in check_throttles
    if not throttle.allow_request(request, self):
  File "D:\src\smarterwms\shopee\utils\throttle.py", line 17, in allow_request
    openid = request.auth.openid
AttributeError: 'NoneType' object has no attribute 'openid'
[2022-11-02 19:19:11,736] [basehttp.py:187] [basehttp:log_message] [ERROR]- "GET /order/?max_page=30&record= HTTP/1.1" 500 116536
[2022-11-02 19:19:11,736] [basehttp.py:187] [basehttp:log_message] [ERROR]- "GET /order/?max_page=30&record= HTTP/1.1" 500 116536
[2022-11-02 19:19:11,941] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /order/
Traceback (most recent call last):
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 416, in initial
    self.check_throttles(request)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 359, in check_throttles
    if not throttle.allow_request(request, self):
  File "D:\src\smarterwms\shopee\utils\throttle.py", line 17, in allow_request
    openid = request.auth.openid
AttributeError: 'NoneType' object has no attribute 'openid'
[2022-11-02 19:19:11,941] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /order/
Traceback (most recent call last):
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 416, in initial
    self.check_throttles(request)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 359, in check_throttles
    if not throttle.allow_request(request, self):
  File "D:\src\smarterwms\shopee\utils\throttle.py", line 17, in allow_request
    openid = request.auth.openid
AttributeError: 'NoneType' object has no attribute 'openid'
[2022-11-02 19:19:11,960] [basehttp.py:187] [basehttp:log_message] [ERROR]- "GET /order/?max_page=30&record= HTTP/1.1" 500 116536
[2022-11-02 19:19:11,960] [basehttp.py:187] [basehttp:log_message] [ERROR]- "GET /order/?max_page=30&record= HTTP/1.1" 500 116536
[2022-11-02 19:20:12,486] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\utils\throttle.py changed, reloading.
[2022-11-02 19:20:12,486] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\utils\throttle.py changed, reloading.
[2022-11-02 19:20:14,066] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:20:14,266] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:20:14,266] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:20:14,867] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 19:20:14,867] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 19:20:58,854] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\order\views.py changed, reloading.
[2022-11-02 19:20:58,854] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\order\views.py changed, reloading.
[2022-11-02 19:21:00,397] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:21:00,565] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:21:00,566] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:21:01,171] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 19:21:01,171] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 19:23:35,427] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\order\views.py changed, reloading.
[2022-11-02 19:23:35,427] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\order\views.py changed, reloading.
[2022-11-02 19:23:37,026] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:23:37,198] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:23:37,198] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:23:37,895] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 19:23:37,895] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 19:33:57,974] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\store\services\fetchservice.py changed, reloading.
[2022-11-02 19:33:57,974] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\store\services\fetchservice.py changed, reloading.
[2022-11-02 19:33:59,544] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:33:59,727] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:33:59,728] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:34:00,309] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 19:34:00,309] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 19:34:09,700] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/?ordering=-update_time HTTP/1.1" 200 61
[2022-11-02 19:34:09,700] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/?ordering=-update_time HTTP/1.1" 200 61
[2022-11-02 19:34:22,106] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=1 HTTP/1.1" 200 2
[2022-11-02 19:34:22,106] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=1 HTTP/1.1" 200 2
[2022-11-02 19:34:25,363] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=2 HTTP/1.1" 200 2
[2022-11-02 19:34:25,363] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=2 HTTP/1.1" 200 2
[2022-11-02 19:34:26,609] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=1 HTTP/1.1" 200 2
[2022-11-02 19:34:26,609] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=1 HTTP/1.1" 200 2
[2022-11-02 19:34:27,739] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/?ordering=-update_time HTTP/1.1" 200 61
[2022-11-02 19:34:27,739] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/?ordering=-update_time HTTP/1.1" 200 61
[2022-11-02 19:44:24,070] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\store\views.py changed, reloading.
[2022-11-02 19:44:24,070] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\store\views.py changed, reloading.
[2022-11-02 19:44:25,717] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:44:25,907] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:44:25,907] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:44:26,525] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 19:44:26,525] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 19:45:53,478] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=2 HTTP/1.1" 200 2
[2022-11-02 19:45:53,478] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=2 HTTP/1.1" 200 2
[2022-11-02 19:45:53,542] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /order/?max_page=30&record= HTTP/1.1" 200 61
[2022-11-02 19:45:53,542] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /order/?max_page=30&record= HTTP/1.1" 200 61
[2022-11-02 19:45:53,638] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /order/?max_page=30&record= HTTP/1.1" 200 61
[2022-11-02 19:45:53,638] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /order/?max_page=30&record= HTTP/1.1" 200 61
[2022-11-02 19:45:53,732] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /order/?max_page=30&record= HTTP/1.1" 200 61
[2022-11-02 19:45:53,732] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /order/?max_page=30&record= HTTP/1.1" 200 61
[2022-11-02 19:45:54,534] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/?ordering=-update_time HTTP/1.1" 200 61
[2022-11-02 19:45:54,534] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/?ordering=-update_time HTTP/1.1" 200 61
[2022-11-02 19:45:55,674] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=2 HTTP/1.1" 200 2
[2022-11-02 19:45:55,674] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=2 HTTP/1.1" 200 2
[2022-11-02 19:45:55,767] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /order/?max_page=30&record= HTTP/1.1" 200 61
[2022-11-02 19:45:55,767] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /order/?max_page=30&record= HTTP/1.1" 200 61
[2022-11-02 19:45:55,916] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /order/?max_page=30&record= HTTP/1.1" 200 61
[2022-11-02 19:45:55,916] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /order/?max_page=30&record= HTTP/1.1" 200 61
[2022-11-02 19:45:56,006] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /order/?max_page=30&record= HTTP/1.1" 200 61
[2022-11-02 19:45:56,006] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /order/?max_page=30&record= HTTP/1.1" 200 61
[2022-11-02 19:45:56,917] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/?ordering=-update_time HTTP/1.1" 200 61
[2022-11-02 19:45:56,917] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/?ordering=-update_time HTTP/1.1" 200 61
[2022-11-02 19:46:24,428] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/?ordering=-update_time HTTP/1.1" 200 1443
[2022-11-02 19:46:24,428] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/?ordering=-update_time HTTP/1.1" 200 1443
[2022-11-02 19:46:37,187] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/?ordering=-update_time HTTP/1.1" 200 1443
[2022-11-02 19:46:37,187] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/?ordering=-update_time HTTP/1.1" 200 1443
[2022-11-02 19:46:53,689] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/?ordering=-update_time HTTP/1.1" 200 1443
[2022-11-02 19:46:53,689] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/?ordering=-update_time HTTP/1.1" 200 1443
[2022-11-02 19:47:46,925] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/auth?storeId=3 HTTP/1.1" 301 0
[2022-11-02 19:47:46,925] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/auth?storeId=3 HTTP/1.1" 301 0
[2022-11-02 19:47:47,050] [views.py:80] [views:auth] [ERROR]- print_logistics error: StoreInfoModel matching query does not exist.
Traceback (most recent call last):
  File "D:\src\smarterwms\shopee\store\views.py", line 77, in auth
    url = self.store_service.get_shopee_auth_url(user_id, partner_id, partner_key, store_id)
  File "D:\src\smarterwms\shopee\store\services\store_service.py", line 66, in get_shopee_auth_url
    auth_info = self.get_store_token_info(store_id=store_id).info_value
  File "D:\src\smarterwms\shopee\store\services\store_service.py", line 187, in get_store_token_info
    return self.get_store_info(store_id=store_id, shop_id=shop_id, merchant_id=merchant_id, key='auth')
  File "D:\src\smarterwms\shopee\store\services\store_service.py", line 200, in get_store_info
    _store_info = StoreInfoModel.objects.get(store=_store, info_key=key)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
store.models.StoreInfoModel.DoesNotExist: StoreInfoModel matching query does not exist.

[2022-11-02 19:47:47,142] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /store/auth/
Traceback (most recent call last):
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DoesNotExist is not JSON serializable
[2022-11-02 19:47:47,142] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /store/auth/
Traceback (most recent call last):
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DoesNotExist is not JSON serializable
[2022-11-02 19:47:47,200] [basehttp.py:187] [basehttp:log_message] [ERROR]- "GET /store/auth/?storeId=3 HTTP/1.1" 500 115249
[2022-11-02 19:47:47,200] [basehttp.py:187] [basehttp:log_message] [ERROR]- "GET /store/auth/?storeId=3 HTTP/1.1" 500 115249
[2022-11-02 19:52:24,845] [views.py:80] [views:auth] [ERROR]- print_logistics error: StoreInfoModel matching query does not exist.
Traceback (most recent call last):
  File "D:\src\smarterwms\shopee\store\views.py", line 77, in auth
    url = self.store_service.get_shopee_auth_url(user_id, partner_id, partner_key, store_id)
  File "D:\src\smarterwms\shopee\store\services\store_service.py", line 66, in get_shopee_auth_url
    auth_info = self.get_store_token_info(store_id=store_id).info_value
  File "D:\src\smarterwms\shopee\store\services\store_service.py", line 187, in get_store_token_info
    return self.get_store_info(store_id=store_id, shop_id=shop_id, merchant_id=merchant_id, key='auth')
  File "D:\src\smarterwms\shopee\store\services\store_service.py", line 200, in get_store_info
    _store_info = StoreInfoModel.objects.get(store=_store, info_key=key)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
store.models.StoreInfoModel.DoesNotExist: StoreInfoModel matching query does not exist.

[2022-11-02 19:52:24,879] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /store/auth/
Traceback (most recent call last):
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DoesNotExist is not JSON serializable
[2022-11-02 19:52:24,879] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /store/auth/
Traceback (most recent call last):
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DoesNotExist is not JSON serializable
[2022-11-02 19:52:24,917] [basehttp.py:187] [basehttp:log_message] [ERROR]- "GET /store/auth/?storeId=3 HTTP/1.1" 500 115249
[2022-11-02 19:52:24,917] [basehttp.py:187] [basehttp:log_message] [ERROR]- "GET /store/auth/?storeId=3 HTTP/1.1" 500 115249
[2022-11-02 19:54:02,479] [views.py:80] [views:auth] [ERROR]- print_logistics error: StoreInfoModel matching query does not exist.
Traceback (most recent call last):
  File "D:\src\smarterwms\shopee\store\views.py", line 77, in auth
    url = self.store_service.get_shopee_auth_url(user_id, partner_id, partner_key, store_id)
  File "D:\src\smarterwms\shopee\store\services\store_service.py", line 66, in get_shopee_auth_url
    auth_info = self.get_store_token_info(store_id=store_id).info_value
  File "D:\src\smarterwms\shopee\store\services\store_service.py", line 187, in get_store_token_info
    return self.get_store_info(store_id=store_id, shop_id=shop_id, merchant_id=merchant_id, key='auth')
  File "D:\src\smarterwms\shopee\store\services\store_service.py", line 200, in get_store_info
    _store_info = StoreInfoModel.objects.get(store=_store, info_key=key)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
store.models.StoreInfoModel.DoesNotExist: StoreInfoModel matching query does not exist.

[2022-11-02 19:54:02,518] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /store/auth/
Traceback (most recent call last):
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DoesNotExist is not JSON serializable
[2022-11-02 19:54:02,518] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /store/auth/
Traceback (most recent call last):
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DoesNotExist is not JSON serializable
[2022-11-02 19:54:02,548] [basehttp.py:187] [basehttp:log_message] [ERROR]- "GET /store/auth/?storeId=3 HTTP/1.1" 500 115249
[2022-11-02 19:54:02,548] [basehttp.py:187] [basehttp:log_message] [ERROR]- "GET /store/auth/?storeId=3 HTTP/1.1" 500 115249
[2022-11-02 19:55:54,731] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\store\views.py changed, reloading.
[2022-11-02 19:55:54,731] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\store\views.py changed, reloading.
[2022-11-02 19:55:56,291] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:55:56,465] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:55:56,466] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 19:55:57,103] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 19:55:57,103] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 19:56:00,163] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /store/auth/
Traceback (most recent call last):
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\src\smarterwms\shopee\store\views.py", line 76, in auth
    url = self.store_service.get_shopee_auth_url(user_id, partner_id, partner_key, store_id)
  File "D:\src\smarterwms\shopee\store\services\store_service.py", line 66, in get_shopee_auth_url
    auth_info = self.get_store_token_info(store_id=store_id).info_value
  File "D:\src\smarterwms\shopee\store\services\store_service.py", line 187, in get_store_token_info
    return self.get_store_info(store_id=store_id, shop_id=shop_id, merchant_id=merchant_id, key='auth')
  File "D:\src\smarterwms\shopee\store\services\store_service.py", line 200, in get_store_info
    _store_info = StoreInfoModel.objects.get(store=_store, info_key=key)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
store.models.StoreInfoModel.DoesNotExist: StoreInfoModel matching query does not exist.
[2022-11-02 19:56:00,163] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /store/auth/
Traceback (most recent call last):
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\src\smarterwms\shopee\store\views.py", line 76, in auth
    url = self.store_service.get_shopee_auth_url(user_id, partner_id, partner_key, store_id)
  File "D:\src\smarterwms\shopee\store\services\store_service.py", line 66, in get_shopee_auth_url
    auth_info = self.get_store_token_info(store_id=store_id).info_value
  File "D:\src\smarterwms\shopee\store\services\store_service.py", line 187, in get_store_token_info
    return self.get_store_info(store_id=store_id, shop_id=shop_id, merchant_id=merchant_id, key='auth')
  File "D:\src\smarterwms\shopee\store\services\store_service.py", line 200, in get_store_info
    _store_info = StoreInfoModel.objects.get(store=_store, info_key=key)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\models\query.py", line 650, in get
    raise self.model.DoesNotExist(
store.models.StoreInfoModel.DoesNotExist: StoreInfoModel matching query does not exist.
[2022-11-02 19:56:00,202] [basehttp.py:187] [basehttp:log_message] [ERROR]- "GET /store/auth/?storeId=3 HTTP/1.1" 500 130021
[2022-11-02 19:56:00,202] [basehttp.py:187] [basehttp:log_message] [ERROR]- "GET /store/auth/?storeId=3 HTTP/1.1" 500 130021
[2022-11-02 20:01:42,677] [store_service.py:81] [store_service:get_shopee_auth_url] [INFO]- redirect_url: https://erp.superwms.website//store/callback?secret=MjAwMzkzNSw2Zjc5YmY3NDU1ZDk3NWMyNmE4ZWFiMzMzNDljZmVmYWNkMmNlODE5ZmRkNzA2ZGEwOTZjZjJiZmU2MDdiNTkzLDE=
[2022-11-02 20:01:42,703] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/auth/?storeId=3 HTTP/1.1" 200 338
[2022-11-02 20:01:42,703] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/auth/?storeId=3 HTTP/1.1" 200 338
[2022-11-02 20:02:09,848] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/?ordering=-update_time HTTP/1.1" 200 1443
[2022-11-02 20:02:09,848] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/?ordering=-update_time HTTP/1.1" 200 1443
[2022-11-02 20:02:13,943] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=1 HTTP/1.1" 200 282
[2022-11-02 20:02:13,943] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=1 HTTP/1.1" 200 282
[2022-11-02 20:02:13,964] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/global?merchant_id=1309172&type=1&max_page=30 HTTP/1.1" 301 0
[2022-11-02 20:02:13,964] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/global?merchant_id=1309172&type=1&max_page=30 HTTP/1.1" 301 0
[2022-11-02 20:02:14,258] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/global/?merchant_id=1309172&type=1&max_page=30 HTTP/1.1" 200 50773
[2022-11-02 20:02:14,258] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/global/?merchant_id=1309172&type=1&max_page=30 HTTP/1.1" 200 50773
[2022-11-02 20:02:14,551] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/global/?merchant_id=1309172&type=1&max_page=30 HTTP/1.1" 200 50773
[2022-11-02 20:02:14,551] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/global/?merchant_id=1309172&type=1&max_page=30 HTTP/1.1" 200 50773
[2022-11-02 20:02:30,608] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/?ordering=-update_time HTTP/1.1" 200 1443
[2022-11-02 20:02:30,608] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/?ordering=-update_time HTTP/1.1" 200 1443
[2022-11-02 20:02:31,510] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=1 HTTP/1.1" 200 282
[2022-11-02 20:02:31,510] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=1 HTTP/1.1" 200 282
[2022-11-02 20:02:31,849] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/global/?merchant_id=1309172&type=1&max_page=30 HTTP/1.1" 200 50773
[2022-11-02 20:02:31,849] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/global/?merchant_id=1309172&type=1&max_page=30 HTTP/1.1" 200 50773
[2022-11-02 20:02:32,185] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/global/?merchant_id=1309172&type=1&max_page=30 HTTP/1.1" 200 50773
[2022-11-02 20:02:32,185] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/global/?merchant_id=1309172&type=1&max_page=30 HTTP/1.1" 200 50773
[2022-11-02 20:02:40,069] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=2 HTTP/1.1" 200 414
[2022-11-02 20:02:40,069] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=2 HTTP/1.1" 200 414
[2022-11-02 20:02:40,103] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product?ordering=-update_time&shop_id=619322244&type=1&max_page=30 HTTP/1.1" 301 0
[2022-11-02 20:02:40,103] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product?ordering=-update_time&shop_id=619322244&type=1&max_page=30 HTTP/1.1" 301 0
[2022-11-02 20:02:40,650] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=619322244&type=1&max_page=30 HTTP/1.1" 200 82977
[2022-11-02 20:02:40,650] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=619322244&type=1&max_page=30 HTTP/1.1" 200 82977
[2022-11-02 20:02:41,161] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=619322244&type=1&max_page=30 HTTP/1.1" 200 82977
[2022-11-02 20:02:41,161] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=619322244&type=1&max_page=30 HTTP/1.1" 200 82977
[2022-11-02 20:02:53,557] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product?ordering=-update_time&shop_id=721680121&type=1&max_page=30 HTTP/1.1" 301 0
[2022-11-02 20:02:53,557] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product?ordering=-update_time&shop_id=721680121&type=1&max_page=30 HTTP/1.1" 301 0
[2022-11-02 20:02:53,791] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=721680121&type=1&max_page=30 HTTP/1.1" 200 61
[2022-11-02 20:02:53,791] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=721680121&type=1&max_page=30 HTTP/1.1" 200 61
[2022-11-02 20:02:57,981] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=721680121&type=1&max_page=30 HTTP/1.1" 200 61
[2022-11-02 20:02:57,981] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=721680121&type=1&max_page=30 HTTP/1.1" 200 61
[2022-11-02 20:04:00,604] [product_service.py:144] [product_service:sync_by_item_id] [INFO]- Sync 721680121 shop-specific products 15594352650
[2022-11-02 20:04:00,618] [product_service.py:198] [product_service:refresh_product] [INFO]- Get 1 Item Base Info 721680121  ['15594352650']
[2022-11-02 20:04:00,694] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/product/get_item_base_info?partner_id=2003935&shop_id=721680121&timestamp=1667390640&access_token=4a6a475972417250777046634c625a4e&sign=1694f7e1fe10befc145e41cad59655d2675d7dc5e47b923cd4c870707f86f275
[2022-11-02 20:04:00,874] [shopee.py:73] [shopee:async_request] [ERROR]- Shopee Request Error: b'{"request_id":"3eeada8eda85d61060a432742d3dcd20","error":"error_auth","message":"Invalid access_token."}'
[2022-11-02 20:04:00,879] [shopee.py:152] [shopee:refresh_shop_token] [INFO]- Refresh Token Url: https://openplatform.shopee.cn//api/v2/auth/access_token/get?partner_id=2003935&timestamp=1667390640&sign=33abcc52b7ef4980a1367a867c899e8384adc1ca78489539f46674cc691ab759
[2022-11-02 20:04:01,010] [shopee.py:169] [shopee:refresh_shop_token] [ERROR]- Response Error: b'{"error":"error_auth","message":"Invalid refresh_token.","request_id":"bd3705745d647681cfa41a14d61a8920"}'
[2022-11-02 20:04:01,010] [shopee.py:90] [shopee:async_request] [ERROR]- Shopee Request Error: not enough arguments for format string
[2022-11-02 20:04:01,017] [views.py:354] [views:sync] [ERROR]- not enough arguments for format string
Traceback (most recent call last):
  File "D:\src\smarterwms\shopee\store\views.py", line 349, in sync
    self.product_service.sync_by_item_id(shop_id, item_id)
  File "D:\src\smarterwms\shopee\store\services\product_service.py", line 145, in sync_by_item_id
    self.refresh_product(shop_id, [item_id], GlobalService.get_instance().emit_goods)
  File "D:\src\smarterwms\shopee\store\services\product_service.py", line 199, in refresh_product
    ret = shopee.request(url_key='product.get_item_base_info', shop_id=shop_id, method='GET',
  File "D:\src\smarterwms\shopee\utils\shopee.py", line 95, in request
    return asyncio.run(async_request(
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\src\smarterwms\shopee\utils\shopee.py", line 91, in async_request
    raise e
  File "D:\src\smarterwms\shopee\utils\shopee.py", line 77, in async_request
    refresh_shop_token(shop_id=shop_id, merchant_id=merchant_id)
  File "D:\src\smarterwms\shopee\utils\shopee.py", line 170, in refresh_shop_token
    raise ValueError('Unknown Error: %s, Msg: %s' % resp.status_code)
TypeError: not enough arguments for format string

[2022-11-02 20:04:01,043] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /store/product/sync
[2022-11-02 20:04:01,043] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /store/product/sync
[2022-11-02 20:04:01,046] [basehttp.py:187] [basehttp:log_message] [ERROR]- "POST /store/product/sync HTTP/1.1" 500 23
[2022-11-02 20:04:01,046] [basehttp.py:187] [basehttp:log_message] [ERROR]- "POST /store/product/sync HTTP/1.1" 500 23
[2022-11-02 20:09:10,656] [product_service.py:144] [product_service:sync_by_item_id] [INFO]- Sync 721680121 shop-specific products 15594352650
[2022-11-02 20:09:10,660] [product_service.py:198] [product_service:refresh_product] [INFO]- Get 1 Item Base Info 721680121  ['15594352650']
[2022-11-02 20:09:10,717] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/product/get_item_base_info?partner_id=2003935&shop_id=721680121&timestamp=1667390950&access_token=526147797a6c42785442525665776475&sign=8d01841a10f8682aa1211c58c0b1d927bab99f325dbdc20c460426962701a065
[2022-11-02 20:09:10,953] [views.py:354] [views:sync] [ERROR]- 错误:  重复键违反唯一约束"store_product_pkey"
DETAIL:  键值"(id)=(1)" 已经存在

Traceback (most recent call last):
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: 错误:  重复键违反唯一约束"store_product_pkey"
DETAIL:  键值"(id)=(1)" 已经存在


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\src\smarterwms\shopee\store\views.py", line 349, in sync
    self.product_service.sync_by_item_id(shop_id, item_id)
  File "D:\src\smarterwms\shopee\store\services\product_service.py", line 145, in sync_by_item_id
    self.refresh_product(shop_id, [item_id], GlobalService.get_instance().emit_goods)
  File "D:\src\smarterwms\shopee\store\services\product_service.py", line 202, in refresh_product
    self.__save_product(store, item)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "D:\src\smarterwms\shopee\store\services\product_service.py", line 284, in __save_product
    store_product.save()
  File "D:\src\smarterwms\shopee\base\models.py", line 28, in save
    super(BaseModel, self).save(*args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\models\base.py", line 831, in save
    self.save_base(
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\models\base.py", line 882, in save_base
    updated = self._save_table(
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\models\base.py", line 1025, in _save_table
    results = self._do_insert(
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\models\base.py", line 1066, in _do_insert
    return manager._insert(
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\models\query.py", line 1790, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\models\sql\compiler.py", line 1657, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: 错误:  重复键违反唯一约束"store_product_pkey"
DETAIL:  键值"(id)=(1)" 已经存在


[2022-11-02 20:09:10,986] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /store/product/sync
[2022-11-02 20:09:10,986] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /store/product/sync
[2022-11-02 20:09:10,986] [basehttp.py:187] [basehttp:log_message] [ERROR]- "POST /store/product/sync HTTP/1.1" 500 23
[2022-11-02 20:09:10,986] [basehttp.py:187] [basehttp:log_message] [ERROR]- "POST /store/product/sync HTTP/1.1" 500 23
[2022-11-02 20:13:26,744] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\store\services\product_service.py changed, reloading.
[2022-11-02 20:13:26,744] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\store\services\product_service.py changed, reloading.
[2022-11-02 20:13:28,275] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 20:13:28,454] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 20:13:28,454] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 20:13:29,040] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 20:13:29,040] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 20:23:25,861] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\store\services\product_service.py changed, reloading.
[2022-11-02 20:23:25,861] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\store\services\product_service.py changed, reloading.
[2022-11-02 20:23:27,497] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 20:23:27,687] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 20:23:27,687] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 20:23:28,383] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 20:23:28,383] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 20:23:38,117] [product_service.py:144] [product_service:sync_by_item_id] [INFO]- Sync 721680121 shop-specific products 15594352650
[2022-11-02 20:23:38,127] [product_service.py:198] [product_service:refresh_product] [INFO]- Get 1 Item Base Info 721680121  ['15594352650']
[2022-11-02 20:23:38,190] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/product/get_item_base_info?partner_id=2003935&shop_id=721680121&timestamp=1667391818&access_token=526147797a6c42785442525665776475&sign=e7c4e12d1b9b9dbe182efc4d851d582d38da8d6c76fe91e64fbca3557a8fbc15
[2022-11-02 20:23:38,582] [product_service.py:262] [product_service:__save_product] [INFO]- product data 
[2022-11-02 20:23:38,586] [views.py:354] [views:sync] [ERROR]- 错误:  重复键违反唯一约束"store_product_pkey"
DETAIL:  键值"(id)=(2)" 已经存在

Traceback (most recent call last):
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: 错误:  重复键违反唯一约束"store_product_pkey"
DETAIL:  键值"(id)=(2)" 已经存在


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\src\smarterwms\shopee\store\views.py", line 349, in sync
    self.product_service.sync_by_item_id(shop_id, item_id)
  File "D:\src\smarterwms\shopee\store\services\product_service.py", line 145, in sync_by_item_id
    self.refresh_product(shop_id, [item_id], GlobalService.get_instance().emit_goods)
  File "D:\src\smarterwms\shopee\store\services\product_service.py", line 202, in refresh_product
    self.__save_product(store, item)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "D:\src\smarterwms\shopee\store\services\product_service.py", line 285, in __save_product
    store_product.save()
  File "D:\src\smarterwms\shopee\base\models.py", line 28, in save
    super(BaseModel, self).save(*args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\models\base.py", line 831, in save
    self.save_base(
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\models\base.py", line 882, in save_base
    updated = self._save_table(
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\models\base.py", line 1025, in _save_table
    results = self._do_insert(
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\models\base.py", line 1066, in _do_insert
    return manager._insert(
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\models\query.py", line 1790, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\models\sql\compiler.py", line 1657, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: 错误:  重复键违反唯一约束"store_product_pkey"
DETAIL:  键值"(id)=(2)" 已经存在


[2022-11-02 20:23:38,618] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /store/product/sync
[2022-11-02 20:23:38,618] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /store/product/sync
[2022-11-02 20:23:38,620] [basehttp.py:187] [basehttp:log_message] [ERROR]- "POST /store/product/sync HTTP/1.1" 500 23
[2022-11-02 20:23:38,620] [basehttp.py:187] [basehttp:log_message] [ERROR]- "POST /store/product/sync HTTP/1.1" 500 23
[2022-11-02 20:30:09,841] [product_service.py:144] [product_service:sync_by_item_id] [INFO]- Sync 721680121 shop-specific products 15594352650
[2022-11-02 20:30:09,846] [product_service.py:198] [product_service:refresh_product] [INFO]- Get 1 Item Base Info 721680121  ['15594352650']
[2022-11-02 20:30:09,902] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/product/get_item_base_info?partner_id=2003935&shop_id=721680121&timestamp=1667392209&access_token=526147797a6c42785442525665776475&sign=9b10477e48cdb5b6e08af05e2d26d91671790860949a806abb065611c2d53bd9
[2022-11-02 20:30:10,260] [product_service.py:262] [product_service:__save_product] [INFO]- product data 
[2022-11-02 20:30:10,343] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/product/get_model_list?partner_id=2003935&shop_id=721680121&timestamp=1667392210&access_token=526147797a6c42785442525665776475&sign=c9932dfea804b821c29c7b5fa7a5fd1a95c6ee47900f6f6bf26fe05131942f52
[2022-11-02 20:30:10,962] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/global_product/get_global_item_id?partner_id=2003935&merchant_id=1309172&timestamp=1667392210&access_token=7a707551516d657947455a4878437578&sign=3ad671adf7b6cf3cbadc7d9ba1c502f845f35ef8e9cb33ad08d5896d9185325f
[2022-11-02 20:30:11,147] [global_service.py:313] [global_service:refresh_global_product] [INFO]- Get 1 Item Base Info [12697232446]
[2022-11-02 20:30:11,205] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/global_product/get_global_item_info?partner_id=2003935&merchant_id=1309172&timestamp=1667392211&access_token=7a707551516d657947455a4878437578&sign=6bb5d1c2444a7e03158fde3e8acbfd227ea866aaa7bf752ff4c3d6db56d6a789
[2022-11-02 20:30:11,402] [global_service.py:338] [global_service:__save_product] [INFO]- __save_product 
[2022-11-02 20:30:11,475] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/global_product/get_global_model_list?partner_id=2003935&merchant_id=1309172&timestamp=1667392211&access_token=7a707551516d657947455a4878437578&sign=faeb0ce3a4340da6f6b763b03082b757f5aaee091d67ea618d115b4ff15e7c4f
[2022-11-02 20:30:12,582] [global_service.py:296] [global_service:emit_goods] [WARNING]- GLOBAL_PRODUCT_SYNC_EVENT Error: 'ReturnDict' object has no attribute 'is_valid'
Traceback (most recent call last):
  File "D:\src\smarterwms\shopee\store\services\global_service.py", line 294, in emit_goods
    res = ProductServiceClient.get_instance().create(StoreGlobalProductEmitDataSerializer(global_product).data)
  File "D:\src\smarterwms\shopee\store\gRpc\client\global_product.py", line 49, in create
    if not product_details.is_valid(True):
AttributeError: 'ReturnDict' object has no attribute 'is_valid'

[2022-11-02 20:30:13,446] [basehttp.py:187] [basehttp:log_message] [INFO]- "POST /store/product/sync HTTP/1.1" 200 24
[2022-11-02 20:30:13,446] [basehttp.py:187] [basehttp:log_message] [INFO]- "POST /store/product/sync HTTP/1.1" 200 24
[2022-11-02 20:30:13,636] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=721680121&type=1&max_page=30 HTTP/1.1" 200 1287
[2022-11-02 20:30:13,636] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=721680121&type=1&max_page=30 HTTP/1.1" 200 1287
[2022-11-02 20:30:16,604] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=1 HTTP/1.1" 200 282
[2022-11-02 20:30:16,604] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=1 HTTP/1.1" 200 282
[2022-11-02 20:30:16,826] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/global/?merchant_id=1309172&type=1&max_page=30 HTTP/1.1" 200 1099
[2022-11-02 20:30:16,826] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/global/?merchant_id=1309172&type=1&max_page=30 HTTP/1.1" 200 1099
[2022-11-02 20:30:16,967] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/global/?merchant_id=1309172&type=1&max_page=30 HTTP/1.1" 200 1099
[2022-11-02 20:30:16,967] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/global/?merchant_id=1309172&type=1&max_page=30 HTTP/1.1" 200 1099
[2022-11-02 20:31:35,244] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/?ordering=-update_time HTTP/1.1" 200 1443
[2022-11-02 20:31:35,244] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/?ordering=-update_time HTTP/1.1" 200 1443
[2022-11-02 20:31:36,571] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=1 HTTP/1.1" 200 282
[2022-11-02 20:31:36,571] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=1 HTTP/1.1" 200 282
[2022-11-02 20:31:36,718] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/global/?merchant_id=1309172&type=1&max_page=30 HTTP/1.1" 200 1099
[2022-11-02 20:31:36,718] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/global/?merchant_id=1309172&type=1&max_page=30 HTTP/1.1" 200 1099
[2022-11-02 20:31:36,849] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/global/?merchant_id=1309172&type=1&max_page=30 HTTP/1.1" 200 1099
[2022-11-02 20:31:36,849] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/global/?merchant_id=1309172&type=1&max_page=30 HTTP/1.1" 200 1099
[2022-11-02 20:31:37,915] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=2 HTTP/1.1" 200 414
[2022-11-02 20:31:37,915] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=2 HTTP/1.1" 200 414
[2022-11-02 20:31:38,158] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=619322244&type=1&max_page=30 HTTP/1.1" 200 61
[2022-11-02 20:31:38,158] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=619322244&type=1&max_page=30 HTTP/1.1" 200 61
[2022-11-02 20:31:38,255] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=619322244&type=1&max_page=30 HTTP/1.1" 200 61
[2022-11-02 20:31:38,255] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=619322244&type=1&max_page=30 HTTP/1.1" 200 61
[2022-11-02 20:31:39,904] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=1 HTTP/1.1" 200 282
[2022-11-02 20:31:39,904] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=1 HTTP/1.1" 200 282
[2022-11-02 20:31:40,103] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/global/?merchant_id=1309172&type=1&max_page=30 HTTP/1.1" 200 1099
[2022-11-02 20:31:40,103] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/global/?merchant_id=1309172&type=1&max_page=30 HTTP/1.1" 200 1099
[2022-11-02 20:31:40,242] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/global/?merchant_id=1309172&type=1&max_page=30 HTTP/1.1" 200 1099
[2022-11-02 20:31:40,242] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/global/?merchant_id=1309172&type=1&max_page=30 HTTP/1.1" 200 1099
[2022-11-02 20:31:41,535] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=2 HTTP/1.1" 200 414
[2022-11-02 20:31:41,535] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=2 HTTP/1.1" 200 414
[2022-11-02 20:31:41,767] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=619322244&type=1&max_page=30 HTTP/1.1" 200 61
[2022-11-02 20:31:41,767] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=619322244&type=1&max_page=30 HTTP/1.1" 200 61
[2022-11-02 20:31:41,882] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=619322244&type=1&max_page=30 HTTP/1.1" 200 61
[2022-11-02 20:31:41,882] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=619322244&type=1&max_page=30 HTTP/1.1" 200 61
[2022-11-02 20:31:43,397] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=721680121&type=1&max_page=30 HTTP/1.1" 200 1287
[2022-11-02 20:31:43,397] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=721680121&type=1&max_page=30 HTTP/1.1" 200 1287
[2022-11-02 20:39:20,116] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\store\gRpc\client\global_product.py changed, reloading.
[2022-11-02 20:39:20,116] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\store\gRpc\client\global_product.py changed, reloading.
[2022-11-02 20:39:21,685] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 20:39:21,860] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 20:39:21,861] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 20:39:22,619] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 20:39:22,619] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 20:39:45,785] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\store\gRpc\client\global_product.py changed, reloading.
[2022-11-02 20:39:45,785] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\store\gRpc\client\global_product.py changed, reloading.
[2022-11-02 20:39:47,432] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 20:39:47,616] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 20:39:47,616] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 20:39:48,329] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 20:39:48,329] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 20:39:56,838] [product_service.py:144] [product_service:sync_by_item_id] [INFO]- Sync 721680121 shop-specific products 15594352650
[2022-11-02 20:39:56,845] [product_service.py:198] [product_service:refresh_product] [INFO]- Get 1 Item Base Info 721680121  ['15594352650']
[2022-11-02 20:39:56,912] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/product/get_item_base_info?partner_id=2003935&shop_id=721680121&timestamp=1667392796&access_token=526147797a6c42785442525665776475&sign=2221d8d78ed032d55f38bd34044b6faca1d7c3fdb64ef6a2f204fce94f3369b6
[2022-11-02 20:39:57,057] [shopee.py:73] [shopee:async_request] [ERROR]- Shopee Request Error: b'{"request_id":"ec685075c203e46560229ae3d68d5420","error":"error_auth","message":"Invalid access_token."}'
[2022-11-02 20:39:57,070] [shopee.py:152] [shopee:refresh_shop_token] [INFO]- Refresh Token Url: https://openplatform.shopee.cn//api/v2/auth/access_token/get?partner_id=2003935&timestamp=1667392797&sign=98941385b0419e8b32fdd52eeb9860ea0899ccabf2cede89ee60c7f0de4152e9
[2022-11-02 20:39:57,291] [shopee.py:164] [shopee:refresh_shop_token] [INFO]- Refresh Token Success
[2022-11-02 20:39:57,299] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/product/get_item_base_info?partner_id=2003935&shop_id=721680121&timestamp=1667392797&access_token=564965787a6579484c73705849615464&sign=c76f80edda497edd8f78a628731fd6ec977cd2291f7016a08bb27cbf00b32138
[2022-11-02 20:39:57,844] [product_service.py:262] [product_service:__save_product] [INFO]- product data 
[2022-11-02 20:39:57,933] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/product/get_model_list?partner_id=2003935&shop_id=721680121&timestamp=1667392797&access_token=564965787a6579484c73705849615464&sign=3f0859c96148e2e3e12358e20ddc65743417ed40df51940e23c30bd9f8626686
[2022-11-02 20:39:58,543] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/global_product/get_global_item_id?partner_id=2003935&merchant_id=1309172&timestamp=1667392798&access_token=7a707551516d657947455a4878437578&sign=c51e7c41b2b084e7b8a2d71bcac71281f2e00ec1846b0d832b2f1c06fe0ec7bc
[2022-11-02 20:39:58,667] [shopee.py:73] [shopee:async_request] [ERROR]- Shopee Request Error: b'{"request_id":"f68a72e83a4361eea45e70e120c46620","error":"error_auth","message":"Invalid access_token."}'
[2022-11-02 20:39:58,674] [shopee.py:152] [shopee:refresh_shop_token] [INFO]- Refresh Token Url: https://openplatform.shopee.cn//api/v2/auth/access_token/get?partner_id=2003935&timestamp=1667392798&sign=389c019f0b6d0e869ee018154cba6a74c2230d6150da4697527f7ae209e7a8ae
[2022-11-02 20:39:58,823] [shopee.py:164] [shopee:refresh_shop_token] [INFO]- Refresh Token Success
[2022-11-02 20:39:58,831] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/global_product/get_global_item_id?partner_id=2003935&merchant_id=1309172&timestamp=1667392798&access_token=704b6c616279637064774b7057696374&sign=0369c3d3db0b4c493a801b44be037dfa617cc87cb7d2e8bcc2318ac962278e82
[2022-11-02 20:39:58,994] [global_service.py:314] [global_service:refresh_global_product] [INFO]- Get 1 Item Base Info [12697232446]
[2022-11-02 20:39:59,048] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/global_product/get_global_item_info?partner_id=2003935&merchant_id=1309172&timestamp=1667392799&access_token=704b6c616279637064774b7057696374&sign=fde6cdc9abf49f6f997abe1ef5f37e826c750a1d097d38d64dc32e89cb36d701
[2022-11-02 20:39:59,231] [global_service.py:339] [global_service:__save_product] [INFO]- __save_product 
[2022-11-02 20:39:59,321] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/global_product/get_global_model_list?partner_id=2003935&merchant_id=1309172&timestamp=1667392799&access_token=704b6c616279637064774b7057696374&sign=b2871c72325dcce863ddeda8d8fa4d3bd4b2dd23dac7585bad30e8da25601794
[2022-11-02 20:40:02,577] [global_service.py:297] [global_service:emit_goods] [WARNING]- GLOBAL_PRODUCT_SYNC_EVENT Error: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "Method not found!"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:50051 {grpc_message:"Method not found!", grpc_status:12, created_time:"2022-11-02T12:40:02.575593567+00:00"}"
>
Traceback (most recent call last):
  File "D:\src\smarterwms\shopee\store\services\global_service.py", line 294, in emit_goods
    res = ProductServiceClient.get_instance().create_from_shopee(
  File "D:\src\smarterwms\shopee\store\gRpc\client\global_product.py", line 57, in create_from_shopee
    res = self.service_stub.Create(product_details.to_message())
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\grpc\_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\grpc\_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "Method not found!"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:50051 {grpc_message:"Method not found!", grpc_status:12, created_time:"2022-11-02T12:40:02.575593567+00:00"}"
>

[2022-11-02 20:40:03,384] [basehttp.py:187] [basehttp:log_message] [INFO]- "POST /store/product/sync HTTP/1.1" 200 24
[2022-11-02 20:40:03,384] [basehttp.py:187] [basehttp:log_message] [INFO]- "POST /store/product/sync HTTP/1.1" 200 24
[2022-11-02 20:40:03,666] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=721680121&type=1&max_page=30 HTTP/1.1" 200 1287
[2022-11-02 20:40:03,666] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=721680121&type=1&max_page=30 HTTP/1.1" 200 1287
[2022-11-02 20:44:53,843] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\store\gRpc\client\global_product.py changed, reloading.
[2022-11-02 20:44:53,843] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\store\gRpc\client\global_product.py changed, reloading.
[2022-11-02 20:44:55,364] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 20:44:55,540] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 20:44:55,541] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 20:44:56,148] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 20:44:56,148] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 21:12:30,672] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/?ordering=-update_time HTTP/1.1" 200 1443
[2022-11-02 21:12:30,672] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/?ordering=-update_time HTTP/1.1" 200 1443
[2022-11-02 21:12:31,871] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=2 HTTP/1.1" 200 414
[2022-11-02 21:12:31,871] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=2 HTTP/1.1" 200 414
[2022-11-02 21:12:32,020] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=619322244&type=1&max_page=30 HTTP/1.1" 200 61
[2022-11-02 21:12:32,020] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=619322244&type=1&max_page=30 HTTP/1.1" 200 61
[2022-11-02 21:12:32,152] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=619322244&type=1&max_page=30 HTTP/1.1" 200 61
[2022-11-02 21:12:32,152] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=619322244&type=1&max_page=30 HTTP/1.1" 200 61
[2022-11-02 21:12:33,620] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=721680121&type=1&max_page=30 HTTP/1.1" 200 1287
[2022-11-02 21:12:33,620] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=721680121&type=1&max_page=30 HTTP/1.1" 200 1287
[2022-11-02 21:21:03,606] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\store\gRpc\client\global_product.py changed, reloading.
[2022-11-02 21:21:23,019] [product_service.py:144] [product_service:sync_by_item_id] [INFO]- Sync 721680121 shop-specific products 15594352650
[2022-11-02 21:23:25,834] [product_service.py:144] [product_service:sync_by_item_id] [INFO]- Sync 721680121 shop-specific products 15594352650
[2022-11-02 21:21:03,606] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\store\gRpc\client\global_product.py changed, reloading.
[2022-11-02 21:23:43,569] [product_service.py:198] [product_service:refresh_product] [INFO]- Get 1 Item Base Info 721680121  ['15594352650']
[2022-11-02 21:23:45,272] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 21:23:45,445] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 21:23:45,446] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 21:23:46,041] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 21:23:46,041] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 21:23:56,934] [product_service.py:144] [product_service:sync_by_item_id] [INFO]- Sync 721680121 shop-specific products 15594352650
[2022-11-02 21:23:56,942] [product_service.py:198] [product_service:refresh_product] [INFO]- Get 1 Item Base Info 721680121  ['15594352650']
[2022-11-02 21:23:57,010] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/product/get_item_base_info?partner_id=2003935&shop_id=721680121&timestamp=1667395437&access_token=564965787a6579484c73705849615464&sign=47d9176e5ddac192d873fdc78b277465b46ebe838aa00386e896e5115ea684df
[2022-11-02 21:23:57,165] [shopee.py:73] [shopee:async_request] [ERROR]- Shopee Request Error: b'{"request_id":"451373d5a0733e435cdd544dd7e35020","error":"error_auth","message":"Invalid access_token."}'
[2022-11-02 21:23:57,171] [shopee.py:152] [shopee:refresh_shop_token] [INFO]- Refresh Token Url: https://openplatform.shopee.cn//api/v2/auth/access_token/get?partner_id=2003935&timestamp=1667395437&sign=5b7cafed87ac3684dc90c9c75526036885183f25527a34ce2cad085ef29ed027
[2022-11-02 21:23:57,329] [shopee.py:164] [shopee:refresh_shop_token] [INFO]- Refresh Token Success
[2022-11-02 21:23:57,335] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/product/get_item_base_info?partner_id=2003935&shop_id=721680121&timestamp=1667395437&access_token=6f4a49734b6d7a4a6c78697150544f42&sign=80237e1c6211134b6b0cadd66fe55f9f3afe99fcee5cdb9f2cdd717096d03efd
[2022-11-02 21:23:57,642] [product_service.py:262] [product_service:__save_product] [INFO]- product data 
[2022-11-02 21:23:57,707] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/product/get_model_list?partner_id=2003935&shop_id=721680121&timestamp=1667395437&access_token=6f4a49734b6d7a4a6c78697150544f42&sign=a0cf34fb5785635133f10770350ce84e456f212251bc4ceda5e8da3daffada81
[2022-11-02 21:23:58,338] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/global_product/get_global_item_id?partner_id=2003935&merchant_id=1309172&timestamp=1667395438&access_token=704b6c616279637064774b7057696374&sign=10d271d3d7e3f4d757b7dbf6fca0a42abfebffeafbdd671e478b3bc49d1965b1
[2022-11-02 21:23:58,478] [shopee.py:73] [shopee:async_request] [ERROR]- Shopee Request Error: b'{"request_id":"cab82abf727f0c39aedbe698af9d1f20","error":"error_auth","message":"Invalid access_token."}'
[2022-11-02 21:23:58,490] [shopee.py:152] [shopee:refresh_shop_token] [INFO]- Refresh Token Url: https://openplatform.shopee.cn//api/v2/auth/access_token/get?partner_id=2003935&timestamp=1667395438&sign=321b00817b567e0e29edba94ec39d205f92c3d722963f55ecac73a3178c4f770
[2022-11-02 21:23:58,643] [shopee.py:164] [shopee:refresh_shop_token] [INFO]- Refresh Token Success
[2022-11-02 21:23:58,649] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/global_product/get_global_item_id?partner_id=2003935&merchant_id=1309172&timestamp=1667395438&access_token=654f434b6346797a707a776752796279&sign=9c253e0775485daea3e4a14500e5e947ffff362141242d0f881649507e5c6695
[2022-11-02 21:23:58,834] [global_service.py:314] [global_service:refresh_global_product] [INFO]- Get 1 Item Base Info [12697232446]
[2022-11-02 21:23:58,891] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/global_product/get_global_item_info?partner_id=2003935&merchant_id=1309172&timestamp=1667395438&access_token=654f434b6346797a707a776752796279&sign=769603dcc90321ebd089698103fcb86ae685c5b4f5a515e5240bcfdaae525279
[2022-11-02 21:23:59,105] [global_service.py:339] [global_service:__save_product] [INFO]- __save_product 
[2022-11-02 21:23:59,287] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/global_product/get_global_model_list?partner_id=2003935&merchant_id=1309172&timestamp=1667395439&access_token=654f434b6346797a707a776752796279&sign=1724f5ae09b61e08d84cba2867b7ee7740e241ee45f3fa27b1bf7ac8d01c6915
[2022-11-02 21:24:04,411] [global_service.py:297] [global_service:emit_goods] [WARNING]- GLOBAL_PRODUCT_SYNC_EVENT Error: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNAVAILABLE: WSA Error"
	debug_error_string = "UNKNOWN:Failed to pick subchannel {created_time:"2022-11-02T13:24:04.409406714+00:00", children:[UNKNOWN:failed to connect to all addresses; last error: UNAVAILABLE: WSA Error {grpc_status:14, created_time:"2022-11-02T13:24:04.40940387+00:00"}]}"
>
Traceback (most recent call last):
  File "D:\src\smarterwms\shopee\store\services\global_service.py", line 294, in emit_goods
    res = ProductServiceClient.get_instance().create_from_shopee(
  File "D:\src\smarterwms\shopee\store\gRpc\client\global_product.py", line 56, in create_from_shopee
    res = self.service_stub.Create(product_details.to_message())
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\grpc\_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\Users\heqix\anaconda3\envs\GreateWMS\lib\site-packages\grpc\_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNAVAILABLE: WSA Error"
	debug_error_string = "UNKNOWN:Failed to pick subchannel {created_time:"2022-11-02T13:24:04.409406714+00:00", children:[UNKNOWN:failed to connect to all addresses; last error: UNAVAILABLE: WSA Error {grpc_status:14, created_time:"2022-11-02T13:24:04.40940387+00:00"}]}"
>

[2022-11-02 21:24:05,232] [basehttp.py:187] [basehttp:log_message] [INFO]- "POST /store/product/sync HTTP/1.1" 200 24
[2022-11-02 21:24:05,232] [basehttp.py:187] [basehttp:log_message] [INFO]- "POST /store/product/sync HTTP/1.1" 200 24
[2022-11-02 21:24:05,388] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=721680121&type=1&max_page=30 HTTP/1.1" 200 1287
[2022-11-02 21:24:05,388] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=721680121&type=1&max_page=30 HTTP/1.1" 200 1287
[2022-11-02 21:24:39,570] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\store\gRpc\client\global_product.py changed, reloading.
[2022-11-02 21:24:39,570] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\store\gRpc\client\global_product.py changed, reloading.
[2022-11-02 21:24:41,071] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 21:24:41,243] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 21:24:41,243] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 21:24:41,820] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 21:24:41,820] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 21:24:49,781] [product_service.py:144] [product_service:sync_by_item_id] [INFO]- Sync 721680121 shop-specific products 15594352650
[2022-11-02 21:24:49,789] [product_service.py:198] [product_service:refresh_product] [INFO]- Get 1 Item Base Info 721680121  ['15594352650']
[2022-11-02 21:24:49,849] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/product/get_item_base_info?partner_id=2003935&shop_id=721680121&timestamp=1667395489&access_token=6f4a49734b6d7a4a6c78697150544f42&sign=8a05654c435eb3c19e2166ed68ee5979f3b97cc4071f4100c558f8f89d7689c5
[2022-11-02 21:24:50,058] [product_service.py:262] [product_service:__save_product] [INFO]- product data 
[2022-11-02 21:24:50,132] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/product/get_model_list?partner_id=2003935&shop_id=721680121&timestamp=1667395490&access_token=6f4a49734b6d7a4a6c78697150544f42&sign=a5939f0cc962cccc50553a7e51d27e95c6238bfb5848121ffce9039816e2c73e
[2022-11-02 21:24:50,795] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/global_product/get_global_item_id?partner_id=2003935&merchant_id=1309172&timestamp=1667395490&access_token=654f434b6346797a707a776752796279&sign=fe4b81b3ed53c2b4068ca5aa3fd8960515fd178d0ae0f6597d246161950df048
[2022-11-02 21:24:50,984] [global_service.py:314] [global_service:refresh_global_product] [INFO]- Get 1 Item Base Info [12697232446]
[2022-11-02 21:24:51,064] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/global_product/get_global_item_info?partner_id=2003935&merchant_id=1309172&timestamp=1667395491&access_token=654f434b6346797a707a776752796279&sign=ac64091f7443b71fa241f824c2005960cf89457eb17f540b27608ca3bf620473
[2022-11-02 21:24:51,261] [global_service.py:339] [global_service:__save_product] [INFO]- __save_product 
[2022-11-02 21:24:51,343] [shopee.py:33] [shopee:async_request] [INFO]- Shopee Request Url: https://openplatform.shopee.cn//api/v2/global_product/get_global_model_list?partner_id=2003935&merchant_id=1309172&timestamp=1667395491&access_token=654f434b6346797a707a776752796279&sign=53452293090849baef0a58bcb8fae1e55202528c706396aee3b8eb366577c8dd
[2022-11-02 21:24:52,629] [global_service.py:302] [global_service:emit_goods] [INFO]- Create product Baby&KidsFashion_20221026_038D success
[2022-11-02 21:24:53,367] [basehttp.py:187] [basehttp:log_message] [INFO]- "POST /store/product/sync HTTP/1.1" 200 24
[2022-11-02 21:24:53,367] [basehttp.py:187] [basehttp:log_message] [INFO]- "POST /store/product/sync HTTP/1.1" 200 24
[2022-11-02 21:24:53,536] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=721680121&type=1&max_page=30 HTTP/1.1" 200 1287
[2022-11-02 21:24:53,536] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=721680121&type=1&max_page=30 HTTP/1.1" 200 1287
[2022-11-02 21:25:06,038] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/?ordering=-update_time HTTP/1.1" 200 1443
[2022-11-02 21:25:06,038] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/?ordering=-update_time HTTP/1.1" 200 1443
[2022-11-02 21:25:06,898] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=2 HTTP/1.1" 200 414
[2022-11-02 21:25:06,898] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/all/?type=2 HTTP/1.1" 200 414
[2022-11-02 21:25:07,130] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=619322244&type=1&max_page=30 HTTP/1.1" 200 61
[2022-11-02 21:25:07,130] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=619322244&type=1&max_page=30 HTTP/1.1" 200 61
[2022-11-02 21:25:07,278] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=619322244&type=1&max_page=30 HTTP/1.1" 200 61
[2022-11-02 21:25:07,278] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=619322244&type=1&max_page=30 HTTP/1.1" 200 61
[2022-11-02 21:25:10,050] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=721680121&type=1&max_page=30 HTTP/1.1" 200 1287
[2022-11-02 21:25:10,050] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /store/product/?ordering=-update_time&shop_id=721680121&type=1&max_page=30 HTTP/1.1" 200 1287
[2022-11-02 21:25:45,178] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 21:25:45,356] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 21:25:45,357] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 21:25:47,317] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 21:25:47,521] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 21:25:47,521] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 21:25:48,167] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 21:25:48,167] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 23:02:11,294] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\publish\models.py changed, reloading.
[2022-11-02 23:02:11,294] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\publish\models.py changed, reloading.
[2022-11-02 23:02:13,276] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:02:13,460] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:02:13,461] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:02:14,116] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 23:02:14,116] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 23:02:35,187] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\publish\models.py changed, reloading.
[2022-11-02 23:02:35,187] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\publish\models.py changed, reloading.
[2022-11-02 23:02:36,784] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:02:36,967] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:02:36,967] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:02:37,633] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 23:02:37,633] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 23:02:54,406] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:02:54,578] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:02:54,579] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:03:08,753] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:03:08,929] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:03:08,929] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:06:09,146] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:06:09,327] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:06:09,328] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:06:11,375] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:06:11,556] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:06:11,557] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:06:12,166] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 23:06:12,166] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 23:09:44,868] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\store\services\global_service.py changed, reloading.
[2022-11-02 23:09:44,868] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\store\services\global_service.py changed, reloading.
[2022-11-02 23:09:46,486] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:09:46,654] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 23:09:46,654] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 23:25:32,359] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\globalproduct\models.py changed, reloading.
[2022-11-02 23:25:32,359] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\globalproduct\models.py changed, reloading.
[2022-11-02 23:25:33,910] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:25:34,040] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 23:25:34,040] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 23:26:00,841] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\stock\services\stockprovider.py changed, reloading.
[2022-11-02 23:26:00,841] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\stock\services\stockprovider.py changed, reloading.
[2022-11-02 23:26:02,259] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:26:02,418] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 23:26:02,418] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 23:26:18,494] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\globalproduct\gRpc\client\global_product.py changed, reloading.
[2022-11-02 23:26:18,494] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- D:\src\smarterwms\shopee\globalproduct\gRpc\client\global_product.py changed, reloading.
[2022-11-02 23:26:19,959] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:26:20,128] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:26:20,128] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:26:20,704] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 23:26:20,704] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-11-02 23:26:37,826] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:26:37,984] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:26:37,985] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:27:13,181] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:27:13,343] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:27:13,344] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:27:24,518] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:27:24,692] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-11-02 23:27:24,692] [base.py:444] [base:add_job] [INFO]- Adding job tentatively -- it will be properly scheduled when the scheduler starts
